version: '3.8'

services:
  # Core PourfectApp library demonstrating containerised DevOps practices
  pourfectapp-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pourfectapp-core
    environment:
      - DOTNET_ENVIRONMENT=Production
    networks:
      - pourfect-network
    restart: "no"  # Runs health check and exits
    healthcheck:
      test: ["CMD", "/app/health.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

# Network for container isolation
networks:
  pourfect-network:
    driver: bridge
